/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models



import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*
import java.time.*
import java.time.format.*
/**
 * 
 * @param sivilstand 
 * @param aarsak 
 * @param ajourholdstidspunkt 
 * @param erGjeldende 
 * @param gyldighetstidspunkt 
 * @param kilde 
 * @param kommune 
 * @param myndighet 
 * @param opphoerstidspunkt 
 * @param relatertVedSivilstand 
 * @param sivilstandsdato 
 * @param sted 
 * @param utland 
 */
data class Folkeregisterettilgjengeliggjoeringpersonv1Sivilstand(
    @field:JsonProperty("sivilstand")
    val sivilstand: Folkeregisterettilgjengeliggjoeringpersonv1Sivilstand.Sivilstand,
    @field:JsonProperty("aarsak")
    val aarsak: kotlin.String? = null,
    @field:JsonProperty("ajourholdstidspunkt")
    val ajourholdstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("erGjeldende")
    val erGjeldende: kotlin.Boolean? = null,
    @field:JsonProperty("gyldighetstidspunkt")
    val gyldighetstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("kilde")
    val kilde: kotlin.String? = null,
    @field:JsonProperty("kommune")
    val kommune: kotlin.String? = null,
    @field:JsonProperty("myndighet")
    val myndighet: kotlin.String? = null,
    @field:JsonProperty("opphoerstidspunkt")
    val opphoerstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("relatertVedSivilstand")
    val relatertVedSivilstand: kotlin.String? = null,
    @field:JsonProperty("sivilstandsdato")
    val sivilstandsdato: java.time.LocalDate? = null,
    @field:JsonProperty("sted")
    val sted: kotlin.String? = null,
    @field:JsonProperty("utland")
    val utland: kotlin.String? = null
) 
{
    /**
    * 
    * Values: uoppgitt,ugift,gift,enkeEllerEnkemann,skilt,separert,registrertPartner,separertPartner,skiltPartner,gjenlevendePartner
    */
    enum class Sivilstand(val value: kotlin.String){
        uoppgitt("uoppgitt"),
        ugift("ugift"),
        gift("gift"),
        enkeEllerEnkemann("enkeEllerEnkemann"),
        skilt("skilt"),
        separert("separert"),
        registrertPartner("registrertPartner"),
        separertPartner("separertPartner"),
        skiltPartner("skiltPartner"),
        gjenlevendePartner("gjenlevendePartner");
    }
    class ParsedValues{
        var sivilstand: Folkeregisterettilgjengeliggjoeringpersonv1Sivilstand.Sivilstand? = null
        var aarsak: kotlin.String? = null
        var ajourholdstidspunkt: java.time.OffsetDateTime? = null
        var erGjeldende: kotlin.Boolean? = null
        var gyldighetstidspunkt: java.time.OffsetDateTime? = null
        var kilde: kotlin.String? = null
        var kommune: kotlin.String? = null
        var myndighet: kotlin.String? = null
        var opphoerstidspunkt: java.time.OffsetDateTime? = null
        var relatertVedSivilstand: kotlin.String? = null
        var sivilstandsdato: java.time.LocalDate? = null
        var sted: kotlin.String? = null
        var utland: kotlin.String? = null
    }

    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringpersonv1Sivilstand>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringpersonv1Sivilstand {
            val parsedValues = ParsedValues()

            var curr = p.currentToken

            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }

            curr = p.nextToken()

            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {

                    "sivilstand" -> parsedValues.sivilstand = Folkeregisterettilgjengeliggjoeringpersonv1Sivilstand.Sivilstand.valueOf(p.text)

                    "aarsak" -> parsedValues.aarsak = p.text
                    "ajourholdstidspunkt" -> parsedValues.ajourholdstidspunkt = OffsetDateTime.parse(p.text)
                    "erGjeldende" -> parsedValues.erGjeldende = p.text.toBoolean()
                    "gyldighetstidspunkt" -> parsedValues.gyldighetstidspunkt = OffsetDateTime.parse(p.text)
                    "kilde" -> parsedValues.kilde = p.text
                    "kommune" -> parsedValues.kommune = p.text
                    "myndighet" -> parsedValues.myndighet = p.text
                    "opphoerstidspunkt" -> parsedValues.opphoerstidspunkt = OffsetDateTime.parse(p.text)
                    "relatertVedSivilstand" -> parsedValues.relatertVedSivilstand = p.text
                    "sivilstandsdato" -> parsedValues.sivilstandsdato = LocalDate.parse(p.text)
                    "sted" -> parsedValues.sted = p.text
                    "utland" -> parsedValues.utland = p.text

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }

            return Folkeregisterettilgjengeliggjoeringpersonv1Sivilstand(
                sivilstand = parsedValues.sivilstand!!,
                aarsak = parsedValues.aarsak,
                ajourholdstidspunkt = parsedValues.ajourholdstidspunkt,
                erGjeldende = parsedValues.erGjeldende,
                gyldighetstidspunkt = parsedValues.gyldighetstidspunkt,
                kilde = parsedValues.kilde,
                kommune = parsedValues.kommune,
                myndighet = parsedValues.myndighet,
                opphoerstidspunkt = parsedValues.opphoerstidspunkt,
                relatertVedSivilstand = parsedValues.relatertVedSivilstand,
                sivilstandsdato = parsedValues.sivilstandsdato,
                sted = parsedValues.sted,
                utland = parsedValues.utland,)
        }
    }

    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }
}
