/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models

import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1RelatertBiPerson

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*


/**
 * 
 *
 * @param relatertPersonsRolle 
 * @param aarsak 
 * @param ajourholdstidspunkt 
 * @param gyldighetstidspunkt 
 * @param kilde 
 * @param minRolleForPerson 
 * @param opphoerstidspunkt 
 * @param relatertPerson 
 * @param relatertPersonUtenFolkeregisteridentifikator 
 */

data class Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon (

    @field:JsonProperty("relatertPersonsRolle")
    val relatertPersonsRolle: Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon.RelatertPersonsRolle,

    @field:JsonProperty("aarsak")
    val aarsak: kotlin.String? = null,

    @field:JsonProperty("ajourholdstidspunkt")
    val ajourholdstidspunkt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("gyldighetstidspunkt")
    val gyldighetstidspunkt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("kilde")
    val kilde: kotlin.String? = null,

    @field:JsonProperty("minRolleForPerson")
    val minRolleForPerson: Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon.MinRolleForPerson? = null,

    @field:JsonProperty("opphoerstidspunkt")
    val opphoerstidspunkt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("relatertPerson")
    val relatertPerson: kotlin.String? = null,

    @field:JsonProperty("relatertPersonUtenFolkeregisteridentifikator")
    val relatertPersonUtenFolkeregisteridentifikator: Folkeregisterettilgjengeliggjoeringhendelsev1RelatertBiPerson? = null

) {

    /**
     * 
     *
     * Values: mor,far,medmor,barn,soesken,ektefelleEllerPartner,doedfoedtBarn
     */
    enum class RelatertPersonsRolle(val value: kotlin.String) {
        @JsonProperty(value = "mor") mor("mor"),
        @JsonProperty(value = "far") far("far"),
        @JsonProperty(value = "medmor") medmor("medmor"),
        @JsonProperty(value = "barn") barn("barn"),
        @JsonProperty(value = "soesken") soesken("soesken"),
        @JsonProperty(value = "ektefelleEllerPartner") ektefelleEllerPartner("ektefelleEllerPartner"),
        @JsonProperty(value = "doedfoedtBarn") doedfoedtBarn("doedfoedtBarn");
    }
    /**
     * 
     *
     * Values: mor,far,medmor,barn,soesken,ektefelleEllerPartner,doedfoedtBarn
     */
    enum class MinRolleForPerson(val value: kotlin.String) {
        @JsonProperty(value = "mor") mor("mor"),
        @JsonProperty(value = "far") far("far"),
        @JsonProperty(value = "medmor") medmor("medmor"),
        @JsonProperty(value = "barn") barn("barn"),
        @JsonProperty(value = "soesken") soesken("soesken"),
        @JsonProperty(value = "ektefelleEllerPartner") ektefelleEllerPartner("ektefelleEllerPartner"),
        @JsonProperty(value = "doedfoedtBarn") doedfoedtBarn("doedfoedtBarn");
    }
    class ParsedValues{
        var relatertPersonsRolle: Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon.RelatertPersonsRolle? = null
        var aarsak: kotlin.String? = null
        var ajourholdstidspunkt: java.time.OffsetDateTime? = null
        var gyldighetstidspunkt: java.time.OffsetDateTime? = null
        var kilde: kotlin.String? = null
        var minRolleForPerson: Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon.MinRolleForPerson? = null
        var opphoerstidspunkt: java.time.OffsetDateTime? = null
        var relatertPerson: kotlin.String? = null
        var relatertPersonUtenFolkeregisteridentifikator: Folkeregisterettilgjengeliggjoeringhendelsev1RelatertBiPerson? = null
    }

    @Suppress("UNUSED_VALUE")
    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon {
            val parsedValues = ParsedValues()
            var curr = p.currentToken
            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }
            curr = p.nextToken()
            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {

                    "relatertPersonsRolle" -> parsedValues.relatertPersonsRolle = Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon.RelatertPersonsRolle.valueOf(p.text)

                    "aarsak" -> parsedValues.aarsak = p.text
                    "ajourholdstidspunkt" -> parsedValues.ajourholdstidspunkt = java.time.OffsetDateTime.parse(p.text)
                    "gyldighetstidspunkt" -> parsedValues.gyldighetstidspunkt = java.time.OffsetDateTime.parse(p.text)
                    "kilde" -> parsedValues.kilde = p.text

                    "minRolleForPerson" -> parsedValues.minRolleForPerson = Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon.MinRolleForPerson.valueOf(p.text)
                    "opphoerstidspunkt" -> parsedValues.opphoerstidspunkt = java.time.OffsetDateTime.parse(p.text)
                    "relatertPerson" -> parsedValues.relatertPerson = p.text
                    "relatertPersonUtenFolkeregisteridentifikator" -> parsedValues.relatertPersonUtenFolkeregisteridentifikator = Folkeregisterettilgjengeliggjoeringhendelsev1RelatertBiPerson.deserializer.deserialize(p, ctx)

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }
            return Folkeregisterettilgjengeliggjoeringhendelsev1Familierelasjon(
                relatertPersonsRolle = parsedValues.relatertPersonsRolle!!,
                aarsak = parsedValues.aarsak,
                ajourholdstidspunkt = parsedValues.ajourholdstidspunkt,
                gyldighetstidspunkt = parsedValues.gyldighetstidspunkt,
                kilde = parsedValues.kilde,
                minRolleForPerson = parsedValues.minRolleForPerson,
                opphoerstidspunkt = parsedValues.opphoerstidspunkt,
                relatertPerson = parsedValues.relatertPerson,
                relatertPersonUtenFolkeregisteridentifikator = parsedValues.relatertPersonUtenFolkeregisteridentifikator,)
        }
    }
    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }

}

