/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models

import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1AdvokatSomKontakt
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseForDoedsbo
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1OrganisasjonSomKontakt
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1PersonSomKontakt


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*
import java.time.*
import java.time.format.*
/**
 * 
 * @param adresse 
 * @param attestutstedelsesdato 
 * @param skifteform 
 * @param aarsak 
 * @param advokat 
 * @param ajourholdstidspunkt 
 * @param gyldighetstidspunkt 
 * @param kilde 
 * @param opphoerstidspunkt 
 * @param organisasjon 
 * @param person 
 */
data class Folkeregisterettilgjengeliggjoeringhendelsev1KontaktinformasjonForDoedsbo(
    @field:JsonProperty("adresse")
    val adresse: Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseForDoedsbo,
    @field:JsonProperty("attestutstedelsesdato")
    val attestutstedelsesdato: java.time.LocalDate,
    @field:JsonProperty("skifteform")
    val skifteform: Folkeregisterettilgjengeliggjoeringhendelsev1KontaktinformasjonForDoedsbo.Skifteform,
    @field:JsonProperty("aarsak")
    val aarsak: kotlin.String? = null,
    @field:JsonProperty("advokat")
    val advokat: Folkeregisterettilgjengeliggjoeringhendelsev1AdvokatSomKontakt? = null,
    @field:JsonProperty("ajourholdstidspunkt")
    val ajourholdstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("gyldighetstidspunkt")
    val gyldighetstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("kilde")
    val kilde: kotlin.String? = null,
    @field:JsonProperty("opphoerstidspunkt")
    val opphoerstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("organisasjon")
    val organisasjon: Folkeregisterettilgjengeliggjoeringhendelsev1OrganisasjonSomKontakt? = null,
    @field:JsonProperty("person")
    val person: Folkeregisterettilgjengeliggjoeringhendelsev1PersonSomKontakt? = null
) 
{
    /**
    * 
    * Values: offentlig,annet
    */
    enum class Skifteform(val value: kotlin.String){
        offentlig("offentlig"),
        annet("annet");
    }
    class ParsedValues{
        var adresse: Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseForDoedsbo? = null
        var attestutstedelsesdato: java.time.LocalDate? = null
        var skifteform: Folkeregisterettilgjengeliggjoeringhendelsev1KontaktinformasjonForDoedsbo.Skifteform? = null
        var aarsak: kotlin.String? = null
        var advokat: Folkeregisterettilgjengeliggjoeringhendelsev1AdvokatSomKontakt? = null
        var ajourholdstidspunkt: java.time.OffsetDateTime? = null
        var gyldighetstidspunkt: java.time.OffsetDateTime? = null
        var kilde: kotlin.String? = null
        var opphoerstidspunkt: java.time.OffsetDateTime? = null
        var organisasjon: Folkeregisterettilgjengeliggjoeringhendelsev1OrganisasjonSomKontakt? = null
        var person: Folkeregisterettilgjengeliggjoeringhendelsev1PersonSomKontakt? = null
    }

    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringhendelsev1KontaktinformasjonForDoedsbo>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringhendelsev1KontaktinformasjonForDoedsbo {
            val parsedValues = ParsedValues()

            var curr = p.currentToken

            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }

            curr = p.nextToken()

            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {
                    "adresse" -> parsedValues.adresse = Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseForDoedsbo.deserializer.deserialize(p, ctx)
                    "attestutstedelsesdato" -> parsedValues.attestutstedelsesdato = LocalDate.parse(p.text)

                    "skifteform" -> parsedValues.skifteform = Folkeregisterettilgjengeliggjoeringhendelsev1KontaktinformasjonForDoedsbo.Skifteform.valueOf(p.text)

                    "aarsak" -> parsedValues.aarsak = p.text
                    "advokat" -> parsedValues.advokat = Folkeregisterettilgjengeliggjoeringhendelsev1AdvokatSomKontakt.deserializer.deserialize(p, ctx)
                    "ajourholdstidspunkt" -> parsedValues.ajourholdstidspunkt = OffsetDateTime.parse(p.text)
                    "gyldighetstidspunkt" -> parsedValues.gyldighetstidspunkt = OffsetDateTime.parse(p.text)
                    "kilde" -> parsedValues.kilde = p.text
                    "opphoerstidspunkt" -> parsedValues.opphoerstidspunkt = OffsetDateTime.parse(p.text)
                    "organisasjon" -> parsedValues.organisasjon = Folkeregisterettilgjengeliggjoeringhendelsev1OrganisasjonSomKontakt.deserializer.deserialize(p, ctx)
                    "person" -> parsedValues.person = Folkeregisterettilgjengeliggjoeringhendelsev1PersonSomKontakt.deserializer.deserialize(p, ctx)

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }

            return Folkeregisterettilgjengeliggjoeringhendelsev1KontaktinformasjonForDoedsbo(
                adresse = parsedValues.adresse!!,
                attestutstedelsesdato = parsedValues.attestutstedelsesdato!!,
                skifteform = parsedValues.skifteform!!,
                aarsak = parsedValues.aarsak,
                advokat = parsedValues.advokat,
                ajourholdstidspunkt = parsedValues.ajourholdstidspunkt,
                gyldighetstidspunkt = parsedValues.gyldighetstidspunkt,
                kilde = parsedValues.kilde,
                opphoerstidspunkt = parsedValues.opphoerstidspunkt,
                organisasjon = parsedValues.organisasjon,
                person = parsedValues.person,)
        }
    }

    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }
}
