/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models

import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringpersonv1Adressenummer
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringpersonv1Poststed


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*
import java.time.*
import java.time.format.*
/**
 * 
 * @param adressenavn 
 * @param kommunenummer 
 * @param adressekode 
 * @param adressenummer 
 * @param adressetilleggsnavn 
 * @param bruksenhetsnummer 
 * @param bruksenhetstype 
 * @param coAdressenavn 
 * @param poststed 
 */
data class Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse(
    @field:JsonProperty("adressenavn")
    val adressenavn: kotlin.String,
    @field:JsonProperty("kommunenummer")
    val kommunenummer: kotlin.String,
    @field:JsonProperty("adressekode")
    val adressekode: kotlin.String? = null,
    @field:JsonProperty("adressenummer")
    val adressenummer: Folkeregisterettilgjengeliggjoeringpersonv1Adressenummer? = null,
    @field:JsonProperty("adressetilleggsnavn")
    val adressetilleggsnavn: kotlin.String? = null,
    @field:JsonProperty("bruksenhetsnummer")
    val bruksenhetsnummer: kotlin.String? = null,
    @field:JsonProperty("bruksenhetstype")
    val bruksenhetstype: Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse.Bruksenhetstype? = null,
    @field:JsonProperty("coAdressenavn")
    val coAdressenavn: kotlin.String? = null,
    @field:JsonProperty("poststed")
    val poststed: Folkeregisterettilgjengeliggjoeringpersonv1Poststed? = null
) 
{
    /**
    * 
    * Values: bolig,annetEnnBolig,fritidsbolig,ikkeGodkjentBolig,unummerertBruksenhet
    */
    enum class Bruksenhetstype(val value: kotlin.String){
        bolig("bolig"),
        annetEnnBolig("annetEnnBolig"),
        fritidsbolig("fritidsbolig"),
        ikkeGodkjentBolig("ikkeGodkjentBolig"),
        unummerertBruksenhet("unummerertBruksenhet");
    }
    class ParsedValues{
        var adressenavn: kotlin.String? = null
        var kommunenummer: kotlin.String? = null
        var adressekode: kotlin.String? = null
        var adressenummer: Folkeregisterettilgjengeliggjoeringpersonv1Adressenummer? = null
        var adressetilleggsnavn: kotlin.String? = null
        var bruksenhetsnummer: kotlin.String? = null
        var bruksenhetstype: Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse.Bruksenhetstype? = null
        var coAdressenavn: kotlin.String? = null
        var poststed: Folkeregisterettilgjengeliggjoeringpersonv1Poststed? = null
    }

    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse {
            val parsedValues = ParsedValues()

            var curr = p.currentToken

            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }

            curr = p.nextToken()

            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {
                    "adressenavn" -> parsedValues.adressenavn = p.text
                    "kommunenummer" -> parsedValues.kommunenummer = p.text

                    "adressekode" -> parsedValues.adressekode = p.text
                    "adressenummer" -> parsedValues.adressenummer = Folkeregisterettilgjengeliggjoeringpersonv1Adressenummer.deserializer.deserialize(p, ctx)
                    "adressetilleggsnavn" -> parsedValues.adressetilleggsnavn = p.text
                    "bruksenhetsnummer" -> parsedValues.bruksenhetsnummer = p.text

                    "bruksenhetstype" -> parsedValues.bruksenhetstype = Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse.Bruksenhetstype.valueOf(p.text)
                    "coAdressenavn" -> parsedValues.coAdressenavn = p.text
                    "poststed" -> parsedValues.poststed = Folkeregisterettilgjengeliggjoeringpersonv1Poststed.deserializer.deserialize(p, ctx)

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }

            return Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse(
                adressenavn = parsedValues.adressenavn!!,
                kommunenummer = parsedValues.kommunenummer!!,
                adressekode = parsedValues.adressekode,
                adressenummer = parsedValues.adressenummer,
                adressetilleggsnavn = parsedValues.adressetilleggsnavn,
                bruksenhetsnummer = parsedValues.bruksenhetsnummer,
                bruksenhetstype = parsedValues.bruksenhetstype,
                coAdressenavn = parsedValues.coAdressenavn,
                poststed = parsedValues.poststed,)
        }
    }

    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }
}
