/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models

import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1PostadresseIFrittFormat
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1Postboksadresse
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1VegadresseForPost


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*
import java.time.*
import java.time.format.*
/**
 * 
 * @param adressegradering 
 * @param aarsak 
 * @param adresseIdentifikatorFraMatrikkelen 
 * @param ajourholdstidspunkt 
 * @param gyldighetstidspunkt 
 * @param kilde 
 * @param opphoerstidspunkt 
 * @param postadresseIFrittFormat 
 * @param postboksadresse 
 * @param vegadresse 
 */
data class Folkeregisterettilgjengeliggjoeringhendelsev1Kontaktadresse(
    @field:JsonProperty("adressegradering")
    val adressegradering: Folkeregisterettilgjengeliggjoeringhendelsev1Kontaktadresse.Adressegradering,
    @field:JsonProperty("aarsak")
    val aarsak: kotlin.String? = null,
    @field:JsonProperty("adresseIdentifikatorFraMatrikkelen")
    val adresseIdentifikatorFraMatrikkelen: kotlin.String? = null,
    @field:JsonProperty("ajourholdstidspunkt")
    val ajourholdstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("gyldighetstidspunkt")
    val gyldighetstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("kilde")
    val kilde: kotlin.String? = null,
    @field:JsonProperty("opphoerstidspunkt")
    val opphoerstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("postadresseIFrittFormat")
    val postadresseIFrittFormat: Folkeregisterettilgjengeliggjoeringhendelsev1PostadresseIFrittFormat? = null,
    @field:JsonProperty("postboksadresse")
    val postboksadresse: Folkeregisterettilgjengeliggjoeringhendelsev1Postboksadresse? = null,
    @field:JsonProperty("vegadresse")
    val vegadresse: Folkeregisterettilgjengeliggjoeringhendelsev1VegadresseForPost? = null
) 
{
    /**
    * 
    * Values: ugradert,klientadresse,fortrolig,strengtFortrolig
    */
    enum class Adressegradering(val value: kotlin.String){
        ugradert("ugradert"),
        klientadresse("klientadresse"),
        fortrolig("fortrolig"),
        strengtFortrolig("strengtFortrolig");
    }
    class ParsedValues{
        var adressegradering: Folkeregisterettilgjengeliggjoeringhendelsev1Kontaktadresse.Adressegradering? = null
        var aarsak: kotlin.String? = null
        var adresseIdentifikatorFraMatrikkelen: kotlin.String? = null
        var ajourholdstidspunkt: java.time.OffsetDateTime? = null
        var gyldighetstidspunkt: java.time.OffsetDateTime? = null
        var kilde: kotlin.String? = null
        var opphoerstidspunkt: java.time.OffsetDateTime? = null
        var postadresseIFrittFormat: Folkeregisterettilgjengeliggjoeringhendelsev1PostadresseIFrittFormat? = null
        var postboksadresse: Folkeregisterettilgjengeliggjoeringhendelsev1Postboksadresse? = null
        var vegadresse: Folkeregisterettilgjengeliggjoeringhendelsev1VegadresseForPost? = null
    }

    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringhendelsev1Kontaktadresse>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringhendelsev1Kontaktadresse {
            val parsedValues = ParsedValues()

            var curr = p.currentToken

            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }

            curr = p.nextToken()

            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {

                    "adressegradering" -> parsedValues.adressegradering = Folkeregisterettilgjengeliggjoeringhendelsev1Kontaktadresse.Adressegradering.valueOf(p.text)

                    "aarsak" -> parsedValues.aarsak = p.text
                    "adresseIdentifikatorFraMatrikkelen" -> parsedValues.adresseIdentifikatorFraMatrikkelen = p.text
                    "ajourholdstidspunkt" -> parsedValues.ajourholdstidspunkt = OffsetDateTime.parse(p.text)
                    "gyldighetstidspunkt" -> parsedValues.gyldighetstidspunkt = OffsetDateTime.parse(p.text)
                    "kilde" -> parsedValues.kilde = p.text
                    "opphoerstidspunkt" -> parsedValues.opphoerstidspunkt = OffsetDateTime.parse(p.text)
                    "postadresseIFrittFormat" -> parsedValues.postadresseIFrittFormat = Folkeregisterettilgjengeliggjoeringhendelsev1PostadresseIFrittFormat.deserializer.deserialize(p, ctx)
                    "postboksadresse" -> parsedValues.postboksadresse = Folkeregisterettilgjengeliggjoeringhendelsev1Postboksadresse.deserializer.deserialize(p, ctx)
                    "vegadresse" -> parsedValues.vegadresse = Folkeregisterettilgjengeliggjoeringhendelsev1VegadresseForPost.deserializer.deserialize(p, ctx)

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }

            return Folkeregisterettilgjengeliggjoeringhendelsev1Kontaktadresse(
                adressegradering = parsedValues.adressegradering!!,
                aarsak = parsedValues.aarsak,
                adresseIdentifikatorFraMatrikkelen = parsedValues.adresseIdentifikatorFraMatrikkelen,
                ajourholdstidspunkt = parsedValues.ajourholdstidspunkt,
                gyldighetstidspunkt = parsedValues.gyldighetstidspunkt,
                kilde = parsedValues.kilde,
                opphoerstidspunkt = parsedValues.opphoerstidspunkt,
                postadresseIFrittFormat = parsedValues.postadresseIFrittFormat,
                postboksadresse = parsedValues.postboksadresse,
                vegadresse = parsedValues.vegadresse,)
        }
    }

    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }
}
