/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models



import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*
import java.time.*
import java.time.format.*
/**
 * 
 * @param landkode 
 * @param adresselinje 
 * @param byEllerStedsnavn 
 * @param postkode 
 */
data class Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat(
    @field:JsonProperty("landkode")
    val landkode: kotlin.String,
    @field:JsonProperty("adresselinje")
    val adresselinje: kotlin.collections.List<kotlin.String>? = null,
    @field:JsonProperty("byEllerStedsnavn")
    val byEllerStedsnavn: kotlin.String? = null,
    @field:JsonProperty("postkode")
    val postkode: kotlin.String? = null
) 
{
    class ParsedValues{
        var landkode: kotlin.String? = null
        var adresselinje: List<kotlin.String>? = null
        var byEllerStedsnavn: kotlin.String? = null
        var postkode: kotlin.String? = null
    }

    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat {
            val parsedValues = ParsedValues()

            var curr = p.currentToken

            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }

            curr = p.nextToken()

            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {
                    "landkode" -> parsedValues.landkode = p.text

                    "adresselinje" -> {
                        val list : ArrayList<String> = ArrayList()
                        while(p.nextToken() != JsonToken.END_ARRAY) {
                            list.add(p.text)
                        }
                        parsedValues.adresselinje = list
                      }
                    "byEllerStedsnavn" -> parsedValues.byEllerStedsnavn = p.text
                    "postkode" -> parsedValues.postkode = p.text

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }

            return Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat(
                landkode = parsedValues.landkode!!,
                adresselinje = parsedValues.adresselinje,
                byEllerStedsnavn = parsedValues.byEllerStedsnavn,
                postkode = parsedValues.postkode,)
        }
    }

    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }
}
