/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models

import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkelnummer
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1Poststed

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*


/**
 * 
 *
 * @param matrikkelnummer 
 * @param adressetilleggsnavn 
 * @param bruksenhetsnummer 
 * @param bruksenhetstype 
 * @param coAdressenavn 
 * @param poststed 
 * @param undernummer 
 */

data class Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkeladresse (

    @field:JsonProperty("matrikkelnummer")
    val matrikkelnummer: Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkelnummer,

    @field:JsonProperty("adressetilleggsnavn")
    val adressetilleggsnavn: kotlin.String? = null,

    @field:JsonProperty("bruksenhetsnummer")
    val bruksenhetsnummer: kotlin.String? = null,

    @field:JsonProperty("bruksenhetstype")
    val bruksenhetstype: Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkeladresse.Bruksenhetstype? = null,

    @field:JsonProperty("coAdressenavn")
    val coAdressenavn: kotlin.String? = null,

    @field:JsonProperty("poststed")
    val poststed: Folkeregisterettilgjengeliggjoeringhendelsev1Poststed? = null,

    @field:JsonProperty("undernummer")
    val undernummer: kotlin.Long? = null

) {

    /**
     * 
     *
     * Values: bolig,annetEnnBolig,fritidsbolig,ikkeGodkjentBolig,unummerertBruksenhet
     */
    enum class Bruksenhetstype(val value: kotlin.String) {
        @JsonProperty(value = "bolig") bolig("bolig"),
        @JsonProperty(value = "annetEnnBolig") annetEnnBolig("annetEnnBolig"),
        @JsonProperty(value = "fritidsbolig") fritidsbolig("fritidsbolig"),
        @JsonProperty(value = "ikkeGodkjentBolig") ikkeGodkjentBolig("ikkeGodkjentBolig"),
        @JsonProperty(value = "unummerertBruksenhet") unummerertBruksenhet("unummerertBruksenhet");
    }
    class ParsedValues{
        var matrikkelnummer: Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkelnummer? = null
        var adressetilleggsnavn: kotlin.String? = null
        var bruksenhetsnummer: kotlin.String? = null
        var bruksenhetstype: Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkeladresse.Bruksenhetstype? = null
        var coAdressenavn: kotlin.String? = null
        var poststed: Folkeregisterettilgjengeliggjoeringhendelsev1Poststed? = null
        var undernummer: kotlin.Long? = null
    }

    @Suppress("UNUSED_VALUE")
    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkeladresse>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkeladresse {
            val parsedValues = ParsedValues()
            var curr = p.currentToken
            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }
            curr = p.nextToken()
            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {
                    "matrikkelnummer" -> parsedValues.matrikkelnummer = Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkelnummer.deserializer.deserialize(p, ctx)

                    "adressetilleggsnavn" -> parsedValues.adressetilleggsnavn = p.text
                    "bruksenhetsnummer" -> parsedValues.bruksenhetsnummer = p.text

                    "bruksenhetstype" -> parsedValues.bruksenhetstype = Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkeladresse.Bruksenhetstype.valueOf(p.text)
                    "coAdressenavn" -> parsedValues.coAdressenavn = p.text
                    "poststed" -> parsedValues.poststed = Folkeregisterettilgjengeliggjoeringhendelsev1Poststed.deserializer.deserialize(p, ctx)
                    "undernummer" -> parsedValues.undernummer = p.text.toLong()

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }
            return Folkeregisterettilgjengeliggjoeringhendelsev1Matrikkeladresse(
                matrikkelnummer = parsedValues.matrikkelnummer!!,
                adressetilleggsnavn = parsedValues.adressetilleggsnavn,
                bruksenhetsnummer = parsedValues.bruksenhetsnummer,
                bruksenhetstype = parsedValues.bruksenhetstype,
                coAdressenavn = parsedValues.coAdressenavn,
                poststed = parsedValues.poststed,
                undernummer = parsedValues.undernummer,)
        }
    }
    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }

}

