/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models

import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringpersonv1Matrikkeladresse
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringpersonv1UkjentBosted
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*
import java.time.*
import java.time.format.*
/**
 * 
 * @param adressegradering 
 * @param startdatoForKontrakt 
 * @param aarsak 
 * @param adresseIdentifikatorFraMatrikkelen 
 * @param ajourholdstidspunkt 
 * @param erGjeldende 
 * @param gyldighetstidspunkt 
 * @param kilde 
 * @param matrikkeladresse 
 * @param naerAdresseIdentifikatorFraMatrikkelen 
 * @param opphoerstidspunkt 
 * @param sluttdatoForKontrakt 
 * @param ukjentBosted 
 * @param vegadresse 
 */
data class Folkeregisterettilgjengeliggjoeringpersonv1DeltBosted(
    @field:JsonProperty("adressegradering")
    val adressegradering: Folkeregisterettilgjengeliggjoeringpersonv1DeltBosted.Adressegradering,
    @field:JsonProperty("startdatoForKontrakt")
    val startdatoForKontrakt: java.time.LocalDate,
    @field:JsonProperty("aarsak")
    val aarsak: kotlin.String? = null,
    @field:JsonProperty("adresseIdentifikatorFraMatrikkelen")
    val adresseIdentifikatorFraMatrikkelen: kotlin.String? = null,
    @field:JsonProperty("ajourholdstidspunkt")
    val ajourholdstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("erGjeldende")
    val erGjeldende: kotlin.Boolean? = null,
    @field:JsonProperty("gyldighetstidspunkt")
    val gyldighetstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("kilde")
    val kilde: kotlin.String? = null,
    @field:JsonProperty("matrikkeladresse")
    val matrikkeladresse: Folkeregisterettilgjengeliggjoeringpersonv1Matrikkeladresse? = null,
    @field:JsonProperty("naerAdresseIdentifikatorFraMatrikkelen")
    val naerAdresseIdentifikatorFraMatrikkelen: kotlin.String? = null,
    @field:JsonProperty("opphoerstidspunkt")
    val opphoerstidspunkt: java.time.OffsetDateTime? = null,
    @field:JsonProperty("sluttdatoForKontrakt")
    val sluttdatoForKontrakt: java.time.LocalDate? = null,
    @field:JsonProperty("ukjentBosted")
    val ukjentBosted: Folkeregisterettilgjengeliggjoeringpersonv1UkjentBosted? = null,
    @field:JsonProperty("vegadresse")
    val vegadresse: Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse? = null
) 
{
    /**
    * 
    * Values: ugradert,klientadresse,fortrolig,strengtFortrolig
    */
    enum class Adressegradering(val value: kotlin.String){
        ugradert("ugradert"),
        klientadresse("klientadresse"),
        fortrolig("fortrolig"),
        strengtFortrolig("strengtFortrolig");
    }
    class ParsedValues{
        var adressegradering: Folkeregisterettilgjengeliggjoeringpersonv1DeltBosted.Adressegradering? = null
        var startdatoForKontrakt: java.time.LocalDate? = null
        var aarsak: kotlin.String? = null
        var adresseIdentifikatorFraMatrikkelen: kotlin.String? = null
        var ajourholdstidspunkt: java.time.OffsetDateTime? = null
        var erGjeldende: kotlin.Boolean? = null
        var gyldighetstidspunkt: java.time.OffsetDateTime? = null
        var kilde: kotlin.String? = null
        var matrikkeladresse: Folkeregisterettilgjengeliggjoeringpersonv1Matrikkeladresse? = null
        var naerAdresseIdentifikatorFraMatrikkelen: kotlin.String? = null
        var opphoerstidspunkt: java.time.OffsetDateTime? = null
        var sluttdatoForKontrakt: java.time.LocalDate? = null
        var ukjentBosted: Folkeregisterettilgjengeliggjoeringpersonv1UkjentBosted? = null
        var vegadresse: Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse? = null
    }

    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringpersonv1DeltBosted>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringpersonv1DeltBosted {
            val parsedValues = ParsedValues()

            var curr = p.currentToken

            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }

            curr = p.nextToken()

            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {

                    "adressegradering" -> parsedValues.adressegradering = Folkeregisterettilgjengeliggjoeringpersonv1DeltBosted.Adressegradering.valueOf(p.text)
                    "startdatoForKontrakt" -> parsedValues.startdatoForKontrakt = LocalDate.parse(p.text)

                    "aarsak" -> parsedValues.aarsak = p.text
                    "adresseIdentifikatorFraMatrikkelen" -> parsedValues.adresseIdentifikatorFraMatrikkelen = p.text
                    "ajourholdstidspunkt" -> parsedValues.ajourholdstidspunkt = OffsetDateTime.parse(p.text)
                    "erGjeldende" -> parsedValues.erGjeldende = p.text.toBoolean()
                    "gyldighetstidspunkt" -> parsedValues.gyldighetstidspunkt = OffsetDateTime.parse(p.text)
                    "kilde" -> parsedValues.kilde = p.text
                    "matrikkeladresse" -> parsedValues.matrikkeladresse = Folkeregisterettilgjengeliggjoeringpersonv1Matrikkeladresse.deserializer.deserialize(p, ctx)
                    "naerAdresseIdentifikatorFraMatrikkelen" -> parsedValues.naerAdresseIdentifikatorFraMatrikkelen = p.text
                    "opphoerstidspunkt" -> parsedValues.opphoerstidspunkt = OffsetDateTime.parse(p.text)
                    "sluttdatoForKontrakt" -> parsedValues.sluttdatoForKontrakt = LocalDate.parse(p.text)
                    "ukjentBosted" -> parsedValues.ukjentBosted = Folkeregisterettilgjengeliggjoeringpersonv1UkjentBosted.deserializer.deserialize(p, ctx)
                    "vegadresse" -> parsedValues.vegadresse = Folkeregisterettilgjengeliggjoeringpersonv1Vegadresse.deserializer.deserialize(p, ctx)

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }

            return Folkeregisterettilgjengeliggjoeringpersonv1DeltBosted(
                adressegradering = parsedValues.adressegradering!!,
                startdatoForKontrakt = parsedValues.startdatoForKontrakt!!,
                aarsak = parsedValues.aarsak,
                adresseIdentifikatorFraMatrikkelen = parsedValues.adresseIdentifikatorFraMatrikkelen,
                ajourholdstidspunkt = parsedValues.ajourholdstidspunkt,
                erGjeldende = parsedValues.erGjeldende,
                gyldighetstidspunkt = parsedValues.gyldighetstidspunkt,
                kilde = parsedValues.kilde,
                matrikkeladresse = parsedValues.matrikkeladresse,
                naerAdresseIdentifikatorFraMatrikkelen = parsedValues.naerAdresseIdentifikatorFraMatrikkelen,
                opphoerstidspunkt = parsedValues.opphoerstidspunkt,
                sluttdatoForKontrakt = parsedValues.sluttdatoForKontrakt,
                ukjentBosted = parsedValues.ukjentBosted,
                vegadresse = parsedValues.vegadresse,)
        }
    }

    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }
}
