/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models

import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresse
import im.kny.jacksonspeedup.offentligmedhjemmel.models.Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*


/**
 * 
 *
 * @param adressegradering 
 * @param aarsak 
 * @param ajourholdstidspunkt 
 * @param gyldighetstidspunkt 
 * @param kilde 
 * @param opphoerstidspunkt 
 * @param utenlandskAdresse 
 * @param utenlandskAdresseIFrittFormat 
 */

data class Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseIUtlandet (

    @field:JsonProperty("adressegradering")
    val adressegradering: Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseIUtlandet.Adressegradering,

    @field:JsonProperty("aarsak")
    val aarsak: kotlin.String? = null,

    @field:JsonProperty("ajourholdstidspunkt")
    val ajourholdstidspunkt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("gyldighetstidspunkt")
    val gyldighetstidspunkt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("kilde")
    val kilde: kotlin.String? = null,

    @field:JsonProperty("opphoerstidspunkt")
    val opphoerstidspunkt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("utenlandskAdresse")
    val utenlandskAdresse: Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresse? = null,

    @field:JsonProperty("utenlandskAdresseIFrittFormat")
    val utenlandskAdresseIFrittFormat: Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat? = null

) {

    /**
     * 
     *
     * Values: ugradert,klientadresse,fortrolig,strengtFortrolig
     */
    enum class Adressegradering(val value: kotlin.String) {
        @JsonProperty(value = "ugradert") ugradert("ugradert"),
        @JsonProperty(value = "klientadresse") klientadresse("klientadresse"),
        @JsonProperty(value = "fortrolig") fortrolig("fortrolig"),
        @JsonProperty(value = "strengtFortrolig") strengtFortrolig("strengtFortrolig");
    }
    class ParsedValues{
        var adressegradering: Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseIUtlandet.Adressegradering? = null
        var aarsak: kotlin.String? = null
        var ajourholdstidspunkt: java.time.OffsetDateTime? = null
        var gyldighetstidspunkt: java.time.OffsetDateTime? = null
        var kilde: kotlin.String? = null
        var opphoerstidspunkt: java.time.OffsetDateTime? = null
        var utenlandskAdresse: Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresse? = null
        var utenlandskAdresseIFrittFormat: Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat? = null
    }

    @Suppress("UNUSED_VALUE")
    class Deserializer : JsonDeserializer<Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseIUtlandet>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseIUtlandet {
            val parsedValues = ParsedValues()
            var curr = p.currentToken
            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }
            curr = p.nextToken()
            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {

                    "adressegradering" -> parsedValues.adressegradering = Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseIUtlandet.Adressegradering.valueOf(p.text)

                    "aarsak" -> parsedValues.aarsak = p.text
                    "ajourholdstidspunkt" -> parsedValues.ajourholdstidspunkt = java.time.OffsetDateTime.parse(p.text)
                    "gyldighetstidspunkt" -> parsedValues.gyldighetstidspunkt = java.time.OffsetDateTime.parse(p.text)
                    "kilde" -> parsedValues.kilde = p.text
                    "opphoerstidspunkt" -> parsedValues.opphoerstidspunkt = java.time.OffsetDateTime.parse(p.text)
                    "utenlandskAdresse" -> parsedValues.utenlandskAdresse = Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresse.deserializer.deserialize(p, ctx)
                    "utenlandskAdresseIFrittFormat" -> parsedValues.utenlandskAdresseIFrittFormat = Folkeregisterettilgjengeliggjoeringhendelsev1InternasjonalAdresseIFrittFormat.deserializer.deserialize(p, ctx)

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }
            return Folkeregisterettilgjengeliggjoeringhendelsev1KontaktadresseIUtlandet(
                adressegradering = parsedValues.adressegradering!!,
                aarsak = parsedValues.aarsak,
                ajourholdstidspunkt = parsedValues.ajourholdstidspunkt,
                gyldighetstidspunkt = parsedValues.gyldighetstidspunkt,
                kilde = parsedValues.kilde,
                opphoerstidspunkt = parsedValues.opphoerstidspunkt,
                utenlandskAdresse = parsedValues.utenlandskAdresse,
                utenlandskAdresseIFrittFormat = parsedValues.utenlandskAdresseIFrittFormat,)
        }
    }
    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }

}

