/**
 * Folkeregisteret - offentlig med hjemmel
 *
 * Dokumentasjonen av tjenestene via swaggerhub er under testing.  Beskrivelsene under dokumenterer rettighetspakken Offentlig med hjemmel.  Tilgang til API-et styres med OAuth2-baserte access_tokens.  Mer informasjon om tjenestene, hvordan du får tilgang og finnes på [folkeregisteret-api-dokumentasjon](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/konsumenttjenester/)  Dokumentasjonen kan foreløpig ikke benyttes til kall mot Folkeregisterets testmiljøer.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package im.kny.jacksonspeedup.offentligmedhjemmel.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.type.*


/**
 * 
 *
 * @param ajourholdstidspunkt 
 * @param folkeregisteridentifikator 
 * @param hendelsesdokument 
 * @param hendelsetype 
 * @param persondokument 
 */

data class SkefolkeregisterrettighetspakkehendelserHendelseMedDokumentIdentifikatorer (

    @field:JsonProperty("ajourholdstidspunkt")
    val ajourholdstidspunkt: java.time.OffsetDateTime? = null,

    @field:JsonProperty("folkeregisteridentifikator")
    val folkeregisteridentifikator: kotlin.String? = null,

    @field:JsonProperty("hendelsesdokument")
    val hendelsesdokument: kotlin.String? = null,

    @field:JsonProperty("hendelsetype")
    val hendelsetype: kotlin.String? = null,

    @field:JsonProperty("persondokument")
    val persondokument: kotlin.String? = null

) {

    class ParsedValues{
        var ajourholdstidspunkt: java.time.OffsetDateTime? = null
        var folkeregisteridentifikator: kotlin.String? = null
        var hendelsesdokument: kotlin.String? = null
        var hendelsetype: kotlin.String? = null
        var persondokument: kotlin.String? = null
    }

    @Suppress("UNUSED_VALUE")
    class Deserializer : JsonDeserializer<SkefolkeregisterrettighetspakkehendelserHendelseMedDokumentIdentifikatorer>() {
        override fun deserialize(p: JsonParser, ctx: DeserializationContext): SkefolkeregisterrettighetspakkehendelserHendelseMedDokumentIdentifikatorer {
            val parsedValues = ParsedValues()
            var curr = p.currentToken
            if (curr != JsonToken.START_OBJECT) {
                throw IllegalStateException("Should be start object")
            }
            curr = p.nextToken()
            while (curr == JsonToken.FIELD_NAME) {
                val field = p.text
                curr = p.nextToken()
                when (field) {

                    "ajourholdstidspunkt" -> parsedValues.ajourholdstidspunkt = java.time.OffsetDateTime.parse(p.text)
                    "folkeregisteridentifikator" -> parsedValues.folkeregisteridentifikator = p.text
                    "hendelsesdokument" -> parsedValues.hendelsesdokument = p.text
                    "hendelsetype" -> parsedValues.hendelsetype = p.text
                    "persondokument" -> parsedValues.persondokument = p.text

                    else -> p.skipChildren()
                }
                curr = p.nextToken()
            }
            return SkefolkeregisterrettighetspakkehendelserHendelseMedDokumentIdentifikatorer(
                ajourholdstidspunkt = parsedValues.ajourholdstidspunkt,
                folkeregisteridentifikator = parsedValues.folkeregisteridentifikator,
                hendelsesdokument = parsedValues.hendelsesdokument,
                hendelsetype = parsedValues.hendelsetype,
                persondokument = parsedValues.persondokument,)
        }
    }
    companion object {
        val deserializer by lazy(LazyThreadSafetyMode.NONE) { Deserializer() }
    }

}

